Integrate aws ec2 server
rcltech/sls pull request #25
Opened 2019-09-07 19:24 UTC by 98sean98

Details
- using aws linux 2 and mongodb 4.2 running on the same ec2 instance
- post request by ec2 is only effective if `api_key` sent with json package is correct
- that api_key is not committed to github

Proposed data stream
- esp8266 sends data to `sls` lambda function
- `sls` first sends data to firebase cloud function, then sends same data packaged with `api_key` to ec2 instance
- ec2 instance stores data in mongodb

Deployment method
- `sls` lambda function: push [project root]/lambda folder to production
- ec2 instance: initiate pm2 to keep nodejs server running in background

2019-09-10 04:38 UTC, utkarsh867 requested changes

2019-09-10 04:38 UTC, utkarsh867 commented on ec2/index.js
> +      assert.equal(1, result.result.n);
`result.result.n` not a good way to name the variables. Try to rename and do destructure the variables.

2019-09-10 04:38 UTC, utkarsh867 commented on ec2/index.js
> +app.post('/', (req, res, next) => {
should create separate routes directory to make the route handler

2019-09-10 04:38 UTC, utkarsh867 commented on lambda/index.js
> +const ec2_api_key = require('./.keys/api-key');
we will really need to change this

2019-09-10 04:38 UTC, utkarsh867 commented on lambda/index.js
> +    data.api_key = ec2_api_key;
what is happening here. seems like re-assignment. not good

2019-09-10 04:38 UTC, utkarsh867 commented on ec2/index.js
> +const api_key = require('./.keys/api-key.js')
we definitely need to make some changes here. key files should not exist like this.

2019-09-10 07:39 UTC, 98sean98 commented on lambda/index.js
> +const ec2_api_key = require('./.keys/api-key');
definitely, should be using more secure methods. that was a stop gap measure cuz I was lazy to look up proper ways to create secure keys. should i use `json web token`?

2019-09-10 09:29 UTC, utkarsh867 commented on lambda/index.js
> +const ec2_api_key = require('./.keys/api-key');
i mean we need to be storing these keys as env variables

2019-09-10 09:30 UTC, utkarsh867 commented on ec2/index.js
> +const private_key = require('./.keys/private-key.js')
this does not solve the issue that you are still going to have to put this file manually

2019-09-10 09:44 UTC, 98sean98 commented on lambda/index.js
> +const ec2_api_key = require('./.keys/api-key');
I can implement .env which will be gitignored and use them in lambda and ec2 separately. Should I still try jsonwebtoken to sign and verify the payload using the default HS256 algorithm? Or should I just do that extremely basic check for key equivalence in json payload?

2019-09-10 09:46 UTC, 98sean98 commented on lambda/index.js
> +    data.api_key = ec2_api_key;
Storing the api_key inside the data object, and send it together to ec2

2019-09-10 15:51 UTC, 98sean98 commented on ec2/index.js
> +app.post('/', (req, res, next) => {
there is only one route for this though

2019-09-10 19:12 UTC, 98sean98 commented
- integrated jsonwebtoken
- tested lambda `sls-test` to send data to ec2 server, which managed to store that data in mongodb

2019-09-23 12:14 UTC, utkarsh867 requested changes

2019-09-23 12:14 UTC, utkarsh867 commented on lambda/index.js
>      const firebase_url = "https://us-central1-rcsls-2018.cloudfunctions.net/setWasherStatus"
will be great to put this in env variable as well. generally a good idea so that the program is not dependent on this url

2019-09-23 12:14 UTC, utkarsh867 commented on lambda/index.js
> +    const ec2_url = "http://ec2-52-15-92-86.us-east-2.compute.amazonaws.com:4000";
this url as well

2019-09-23 21:58 UTC, utkarsh867 approved these changes

2019-09-23 21:59 UTC, merged